# Generated by Django 3.1.2 on 2020-10-21 21:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('current_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currents_units', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('coffee_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.coffeetype')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussines.department')),
            ],
        ),
        migrations.CreateModel(
            name='CoffeeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('units', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending status'), ('accepted', 'Accepted status')], default='pending', max_length=8)),
                ('coffee_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.coffeestock')),
            ],
        ),
    ]
